### ISSUE TITLE
CRUD a specific POD

### ISSUE THREAD

**Issue by onionoino** [onionoino/klee#10]
Closes when

1. create a file in POD with Flutter
2. read the file in POD with Flutter
3. update the file in POD with Flutter

**Comment by gjwgit** [comment]
Not yet fully tested - How do I see the update and delete functionality? I see the file created and it seems to be read (to get the last date). Presume it is then straight forward to update and delete.

**Comment by onionoino** [comment]
You are right, I only uses INSERT, UPDATE and SELECT. However, the SOLID specification I read from the github don't support "UPDATE" keyword, so actually if I would like update something, I have to delete it and then insert a new value, so delete, select and insert are all tested and work properly in this application. To abstract the operation, I combine the DELETE and INSERT together to create a new operation UPDATE.

**Comment by onionoino** [comment]
I will update the issue to CRU haha
