### ISSUE TITLE
Allow user to enter their own enc-key

### ISSUE THREAD

**Issue by onionoino** [onionoino/klee#101]
## Description

Allow users to enter their own enc-key in homepage

## Why

So that the open-source will not diclose the enc-key to avoid security issue

## Closing Criteria

- [ ] Allow users to enter their own enc-key in homepage

**Comment by onionoino** [comment]
New features is avaliable in home page now

**Comment by gjwgit** [comment]
How do I get started with the use of the encryption key now?

**Comment by onionoino** [comment]
I have sent you a guide PDF through teams

**Comment by gjwgit** [comment]
Tested
