### ISSUE TITLE
Currently can not login - Exception

### ISSUE THREAD

**Issue by gjwgit** [onionoino/klee#104]
## Description

With the latest update I can no longer authenticate.

## To Replicate

```
$ make linux
```

Click on the Login button and after a second or two I see the following:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: HttpRequestException(502): 
#0      _processResponse (package:solid_auth/src/openid/src/http_util.dart:47:5)
#1      get (package:solid_auth/src/openid/src/http_util.dart:17:10)
<asynchronous suspension>
#2      Issuer.discover (package:solid_auth/src/openid/src/openid.dart:127:16)
<asynchronous suspension>
#3      authenticate (package:solid_auth/solid_auth_client.dart:118:19)
<asynchronous suspension>
#4      LoginPageService.loginAndAuth (package:klee/service/login_page_service.dart:34:12)
<asynchronous suspension>
#5      _LoginPageState.build.<anonymous closure> (package:klee/ui/login_page/login_page.dart:137:49)
<asynchronous suspension>
```

**Comment by onionoino** [comment]
This is highly likely not a problem from my side, Everything was well yesterday, and I upate the solid_auth lib to 0.1.6, than such strange things occur. I can not log into my pod either even if I changed this lib back to 0.1.5. I didn't change any code. I cannot continue my developement now either.

**Comment by onionoino** [comment]
I think we need to talk with the author of this lib?

**Comment by onionoino** [comment]
Ok, seems issue has been resolved, 1. solid_auth is not stable, I degrade it to 0.1.5; 2. ecosysl has some backend problem, because I cannot log into my ecosysl pod by browser either.

![Image](https://user-images.githubusercontent.com/120028393/229467113-53666529-ba71-4c71-b5a3-a512f00f25c2.png)

**Comment by gjwgit** [comment]
0.1.6 is working just fine now with my testing. Perhaps upgrade to it - to remove the Exception over WebView.

**Comment by onionoino** [comment]
Okay, I actually prefer to upgrade it at last - after finishing all charts so that I can develope under a stable environment

**Comment by gjwgit** [comment]
Works for me now.
