### ISSUE TITLE
Add icons to home screen

### ISSUE THREAD

**Issue by gjwgit** [onionoino/klee#106]
## Description

On the home screen perhaps have some white space buffer around the edge of the text and include the tab icon for each section.

Currently it does not look as "attractive" as it might.

![Image](https://user-images.githubusercontent.com/1681429/233231031-be913706-80a6-4d27-b1ce-16b9d512aad6.png)

**Comment by onionoino** [comment]
keyPage and homePage is already fixed in the latest version
