### ISSUE TITLE
Allow the map to be zoomed out to see much more of the region

### ISSUE THREAD

**Issue by gjwgit** [onionoino/klee#11]
Currently I can only zoom only a small extent. I'd like to be able to zoom out much more, at least to see continents etc. The maximum for the current default location zooms out to the following:

![Image](https://user-images.githubusercontent.com/1681429/211715456-437075e2-a333-4d99-baa3-f87f0ef289f9.png)

**Comment by gjwgit** [comment]
What are the parameters around zooming out? Is there a reason to limit it?

**Comment by onionoino** [comment]
Ah, yes you can adjust it on following parameters in osm_page.dart


![Image](https://user-images.githubusercontent.com/120028393/219269514-90ed0183-3518-461b-9e5b-8c1359b8f102.png)

and the max can only be 18, if higher the map cannot display normally? I remembered. But you can adjust the min parameter as you wish. I am currently developing background tasks and I will adjust this along with this PR

**Comment by gjwgit** [comment]
Thanks for the explanation. Very useful to know.
