### ISSUE TITLE
Allow location to be provided

### ISSUE THREAD

**Issue by gjwgit** [onionoino/klee#13]
Sometimes the Location permission may not be granted by the user. 

Allow the user to then enter a location, perhaps some kind of text field or simply a click on the map.

**Comment by gjwgit** [comment]
For the desktop version allow the user to tap on the map to change the location and that will then be recorded as the observation location.

**Comment by onionoino** [comment]
completed, will exhibit in next meeting

**Comment by gjwgit** [comment]
I can now click on the map and change the location. Perfect. Thanks.
