### ISSUE TITLE
On "Enter" keybord press in URL text field mimic click of Login button

### ISSUE THREAD

**Issue by gjwgit** [onionoino/klee#21]
After editing the URL and then pressing Enter perhaps this can trigger a click on the Login button to then attempt a login.

**Comment by gjwgit** [comment]
Please include a comment as to why this item is under review. Yes I can explore and figuire out that it is done and tested it, but each issue in review needs commentary as to why the item is under review.

**Comment by gjwgit** [comment]
This is duplicated in #43

**Comment by onionoino** [comment]
Now you can press ENTER to login when the textfield is focused and url is correctly input
