### ISSUE TITLE
When saving the answers from the form include the variable name being recorded

### ISSUE THREAD

**Issue by gjwgit** [onionoino/klee#31]
The current FORM implementation saves the answers to the questions as q1, q2, q3.

Out of context it doe snot mean much.

Let's record also blood pressure (systolic and diastolic) and heart rate and body temperature.

In the TTL file record these as systolic, diastolic, heart_rate, and body_temperature, and the answer to the two other questions as the value not the choice (like "C").

**Comment by onionoino** [comment]
Ok

**Comment by gjwgit** [comment]
Please explain what was done and why this is now under review.
