### ISSUE TITLE
Override Option

### ISSUE THREAD

**Issue by gjwgit** [onionoino/klee#32]
Currently there is a message about the form already completed for today.

Include in the message the time when the next update can be made (or is it simply once a day kind of thing?)

Perhaps we might allow measurements to be taken after 24 hours (or we might change it to 4 or 8 hours for example).

**Comment by onionoino** [comment]
Yes, I originally designed it simply once a day, I feel it would be too stressful for users to report 2-3 times a day, but if you wish, we could change the frequency, and the notification also works once per day right now

**Comment by onionoino** [comment]
The current mechanism is the survey page will automatically refresh after passing midnight (12:00 a.m), and the notification will work on 9:00 a.m every day. Do you like to change them?

**Comment by onionoino** [comment]
The notification will only come out once per day, if users neglect it, it will not appear again in this day.

**Comment by gjwgit** [comment]
Thanks. Some screenshots here would be good to help the understanding.

**Comment by onionoino** [comment]
![Image](https://user-images.githubusercontent.com/120028393/220130247-2b731c86-ba95-49d1-afed-74aaa1a3db9f.png)

**Comment by gjwgit** [comment]
Can we have two options here please. "Got it" and "Override". If I choose "override" then I can add another report. Best not to frustrate the user.

**Comment by onionoino** [comment]
I will discuss this on thursday with you, because the RDF need to be reworked, so I need to affirm the structure of RDF then design such mechanism

**Comment by onionoino** [comment]
Completed, review on next meeting

**Comment by gjwgit** [comment]
Looks good. Thanks.
