### ISSUE TITLE
Notification Feature

### ISSUE THREAD

**Issue by onionoino** [onionoino/klee#38]
closes when:
1. notifications come out once a day
2. first notification comes out 15 seconds after opening the app if current time passes 9 am
3. notification will not come out before 9 am every day
4. later notifications will come out approx at 9 am every day
5. notifications will guide users to survey page
6. notification could operate even when the app is in background

**Comment by gjwgit** [comment]
Is this in review because it is now functional? Please explain the situation once you move an issue into Review. Thanks.

**Comment by onionoino** [comment]
Sure, it is functional, you can test it according to the description of this issue on your phone
