### ISSUE TITLE
Background GeoInfo Collection

### ISSUE THREAD

**Issue by onionoino** [onionoino/klee#39]
closes when:

AppStatus = { open , paused , closed}

if (the AppStatus is open) {
	// collect geo info every 1 minutes and update the geo info into the POD
} else if (the app is paused) {
	// collect geo info every 15 minutes and store the geo info locally
	// once the AppStatus goes back to open, update local stored information into the POD immediately
} else {
	// nothing we can do if the app is exit, because the OS does not run our codes
}

**Comment by gjwgit** [comment]
Tested and demonstrated.

```
solid@ecosyslnet:~/server/kayon-toga/klee/geo/20230322$ ls
'090633$.ttl'  '090733$.ttl'  '090833$.ttl'  '090933$.ttl'  '091033$.ttl'  
'091133$.ttl'  '091233$.ttl'  '091333$.ttl'  '091433$.ttl'  '091533$.ttl'  
'091633$.ttl'
```
