### ISSUE TITLE
When ENTER is pressed on the https: then LOGIN

### ISSUE THREAD

**Issue by gjwgit** [onionoino/klee#43]
After I edit the text on the URL, at least for the desktop version, it is natural to press ENTER. This should perform the LOGIN, just as if I click the LOGIN button.

![Image](https://user-images.githubusercontent.com/1681429/220006408-e86ec39a-9553-4e12-aef5-85c2c5efce19.png)

**Comment by gjwgit** [comment]
Duplicated

**Comment by onionoino** [comment]
I have thought you gave me two issues stands for two different mechanism, one is for andriod/ios and another one is for desktop platform, now you can both type ENTER on your phone or press "ENTER" on your desktop keyboard to log into your POD

**Comment by gjwgit** [comment]
Thanks!
