### ISSUE TITLE
Add an icon to the app

### ISSUE THREAD

**Issue by gjwgit** [onionoino/klee#44]

**Comment by gjwgit** [comment]
Once in review it needs a description here of what has been done. I don;lt see the icon for example in the linux desktop app.

**Comment by onionoino** [comment]
The Icon can be seen on android and ios platform. Linux is not one of platform need to be supported according to the requirement from the PDF you give me, but if you like, I can search how to change icon in linux. But changing Icon is a native action, need to do differently in different platforms.

**Comment by gjwgit** [comment]
Yes, it gets a little trickier on desktop. There are some guides out there. We've done so for our other apps.

**Comment by gjwgit** [comment]
Not to worry for desktop apps for now - low priority.
