### ISSUE TITLE
RDF structure needs to be corrected

### ISSUE THREAD

**Issue by gjwgit** [onionoino/klee#45]
Klee -> geoInfo -> dayFolder(YYYYmmDD) ->timestamp(HHmmSS).ttl
			   				                  ->timestamp.ttl
                          				                  ->timestamp.ttl
							                     …… (per minute)
	-> surveyInfo
			       -> timestamp(HHmmSS).ttl
-> timestamp.ttl
				…… (per day)

geoInfo - timestamp.ttl 
latitude: xxx
longitude: xxx
…

surveyInfo - timestamp.ttl
cough: xxx
temperature: xxx
latitude: xxx
longitude: xxx
…

**Comment by onionoino** [comment]
Completed, review on next meeting

**Comment by gjwgit** [comment]
Thanks for that. Tested and noting the folder structure klee/survey/*20230226/*190614$.ttl for the survey. 

Contents/RDF looks good.

Is there a reason why the filename begins with a `*`?

**Comment by gjwgit** [comment]
Best no to use `*` in a file name as it is interpreted by the shell as a wildcard.

**Comment by onionoino** [comment]
`*` is deleted now and you can test it
