### ISSUE TITLE
Allow override for missing values

### ISSUE THREAD

**Issue by gjwgit** [onionoino/klee#55]
Allow the user the option to override the below Warning when not all answers have been provided.

![Image](https://user-images.githubusercontent.com/1681429/221434368-e87805fe-a34f-411a-b127-02704ffe905a.png)

**Comment by onionoino** [comment]
This will be very wired, because you tell me not to overwrite but add a new file. So if you only submit part of this report, the new file could be incomplete

**Comment by onionoino** [comment]
Or you would like to say we allow incomplete report to be submitted?

**Comment by onionoino** [comment]
completed, review on Thursday
