### ISSUE TITLE
Plots should go left to right and be intuitive to the user? Edit: rework plots

### ISSUE THREAD

**Issue by gjwgit** [onionoino/klee#76]
The bars in the bar chart seem to be some random order? A time is shown but no date? The bars should indicate data and time and be spread according to the time gaps between observations.

![image](https://user-images.githubusercontent.com/1681429/224856065-fdcc9fbe-0050-4f57-b136-323cc0a8b5ef.png)

Also need an explanation of the symbology. Is this a standard and generally understood symbology, and if not, is there symbology we can use that the general user will understand.

Edit: Rework Plots

**Comment by onionoino** [comment]
Have finished first two, can try it through latest version, line bars will be reworked recently

**Comment by onionoino** [comment]
done

![Image](https://user-images.githubusercontent.com/120028393/234355333-064a74e9-6b6d-43df-acb5-6ff985012e19.png)

**Comment by gjwgit** [comment]
Looking good. Thanks.

**Comment by gjwgit** [comment]
For me, the bars only show the tooltip if the bar is clicked. Whilst the line chart shows the tooltip on hover. Would be good to show the tooltip on hover and click if it is easy to enable.
