### ISSUE TITLE
Update to solid_auth 0.1.6 to fix closeWebView() exception

### ISSUE THREAD

**Issue by gjwgit** [onionoino/klee#97]
## Description

On authenticating solid_auth 0.1.5 is returning an exception. Solution implemented in 0.1.6. Update `pubspec.yaml` to latest versions. Might also check what else can be updated with `flutter pub upgrade --major-versions`.

## Why

So that we maintain currency with latest release to avoid technical debt.

## Closing Criteria

- [ ] No longer see the closeWebView() exception on authenticating a user.

## Detail

```
Opening in existing browser session.
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: UnimplementedError: closeWebView() has not been implemented.
#0      UrlLauncherPlatform.closeWebView (package:url_launcher_platform_interface/src/url_launcher_platform.dart:92:5)
#1      closeInAppWebView (package:url_launcher/src/url_launcher_uri.dart:87:39)
#2      authenticate (package:solid_auth/solid_auth_client.dart:195:5)
```

**Comment by onionoino** [comment]
Sure, I will check it after the meeting

**Comment by gjwgit** [comment]
Updated in 200b8575eacb2680151efaaee597e8e79b5efe16.

**Comment by onionoino** [comment]
done

**Comment by onionoino** [comment]
solid_auth 0.1.6 is not working. I degrade it to 0.1.5

**Comment by gjwgit** [comment]
Is working for me now.

**Comment by onionoino** [comment]
Okay, I will upgrade it at last - after finishing all charts

**Comment by onionoino** [comment]
0.1.6 is not working, please double check with the author of this package, I decide to degrade it and keep it to 0.1.5

It will stuck on this page after upgrading to 0.1.6

![Image](https://user-images.githubusercontent.com/120028393/234356922-1d83d9e0-ca83-43b6-a2f5-e525dff36957.png)
